### ISSUE TITLE
How can i update ldif file?

### ISSUE THREAD

**Issue by scannnn** [asbnotebook/spring-boot#1]
Hi,
I am using Spring embedded LDAP server and i am trying to implement a student information system with LDAP Authentication but in this example and all examples i found in web is just updating or adding users in run time. When i shut down the server and look at my ldif file it is same as the first time. How can i update my ldif file at the same time?

Thanks for any help.

**Comment by asbnotebook** [comment]
Sorry for the late reply. 

Embedded LDAP servers are used for testing purposes. I think you should use an external LDAP server and make the configuration property changes accordingly in the spring boot application to connect to the external LDAP server. With this you should be able to preserve the data even after spring application is shut down.
