### ISSUE TITLE
Getting error while clicking on save button

### ISSUE THREAD

**Issue by Ria36** [asbnotebook/spring-boot#2]
Getting logs :

freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> student.id  [in template "home.ftlh" at line 25, column 59]
![image](https://user-images.githubusercontent.com/52408084/89404716-11809000-d738-11ea-8261-1e6b40301f82.png)

**Comment by asbnotebook** [comment]
Hi @Ria36,

Please make sure that you have imported correct library for the annotations used in the example (Lombok).

```
import lombok.Data;

@Entity
@Data
public class Student {
// private fields..
}
```
